[tools]
"ubi:abhinav/doc2go" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"ubi:miniscruff/changie" = "latest"
go = "1.24.0"

[tasks.build]
run = "go build ./..."
description = "Build the project"

[tasks.test]
description = "Run tests"
run = "go test ./..."

[tasks."test:cover"]
description = "Run tests with coverage"
run = ["go test -coverprofile=cover.out -coverpkg=./... ./..."]

[tasks."test:cover:html"]
description = "Run tests with coverage and generate HTML report"
depends = ["test:cover"]
run = "go tool cover -html=cover.out -o cover.html"

[tasks.lint]
description = "Run all linters"
depends = ["lint:*"]

[tasks."lint:tidy"]
description = "Ensure go.mod is tidy"
run = "go mod tidy -diff"

[tasks."lint:golangci"]
description = "Run golangci-lint"
run = "golangci-lint run"

[tasks."release:prepare"]
description = "Prepare a release"
run = [
  "changie batch {{arg(name='version')}}",
  "changie merge",
]

